### ISSUE TITLE
do not use version below 1.0.0

### ISSUE THREAD

**Issue by bnomei** [fundevogel/kirby3-donuts#2]
upgrading with composer works differently then
0.3.0 in composer json will not upgrade to 0.4.0.
in 1.3.0 in composer it will upgrade to 1.4.0.

**Comment by S1SYPHOS** [comment]
Since I started using specific version numbers instead of ranges, I didn't notice - mucho appreciado!
I will close this issue with v1.0.0 release, as suggested.

**Comment by S1SYPHOS** [comment]
Well, I just released v1.0.0, so this may be closed. Thanks for your efforts, and making open source the community I'm happy to be a part of.
